db:
  image: mysql:5.7.18
  environment:
    MYSQL_ROOT_PASSWORD: test
    MYSQL_DATABASE: ad_application
    MYSQL_USER: test
    MYSQL_PASSWORD: test
  ports:
    - "3306:3306"

memcached:
  image: memcached
  ports:
    - "11211:11211"